[general]
import = [
   # "~/.config/alacritty/themes/tokyo-night-storm.toml",
   "~/.config/alacritty/themes/catppuccin_macchiato.toml",
]

[scrolling]
history = 10000
multiplier = 3

[font]
offset.x = 0
offset.y = 12

[font.normal]
family = "Hack Nerd Font"
style = "Bold"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[terminal]
shell.program = "/opt/homebrew/bin/nu"

[window]
opacity = 0.75
blur = true
decorations = "Transparent"
startup_mode = "Windowed"
dynamic_title = false
title = ""

[window.padding]
x = 10
y = 40
