[[language]]
name = "rust"
auto-format = true
[language-server.rust-analyzer.config.check]
command = "clippy"
[language-server.rust-analyzer.config.cargo]
features = "all"

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[language-server.tinymist]
command = "tinymist"
config = { projectResolution = "lockDatabase", typstExtraArgs = ["--features", "html"], exportPdf = "onType", outputPath = "$root/target/$dir/$name", preview.background.enabled = true, preview.background.args = ["--data-plane-host=127.0.0.1:23635", "--invert-colors=never", "--open"] }

[[language]]
name = "typst"
language-servers = ["tinymist"]
