[symlinks]
"aerospace.toml" = "/Users/vb/.config/aerospace/aerospace.toml"
"alacritty/alacritty.toml" = "/Users/vb/.config/alacritty/alacritty.toml"
"alacritty/themes/catppuccin_macchiato.toml" = "/Users/vb/.config/alacritty/themes/catppuccin_macchiato.toml"
"alacritty/themes/tokyo_night_storm.toml" = "/Users/vb/.config/alacritty/themes/tokyo_night_storm.toml"
"helix/config.toml" = "/Users/vb/.config/helix/config.toml"
"helix/languages.toml" = "/Users/vb/.config/helix/languages.toml"
"helix/themes/catppuccin_macchiato.toml" = "/Users/vb/.config/helix/themes/catppuccin_macchiato.toml"
"kanata/kanata.kbd" = "/Users/vb/.config/kanata/kanata.kbd"
"nushell/config.nu" = "/Users/vb/Library/Application Support/nushell/config.nu"
"nushell/env.nu" = "/Users/vb/Library/Application Support/nushell/env.nu"
"starship.toml" = "/Users/vb/.config/starship.toml"
"yazi/yazi.toml" = "/Users/vb/.config/yazi/yazi.toml"
"zed/settings.json" = "/Users/vb/.config/zed/settings.json"
"zed/tasks.json" = "/Users/vb/.config/zed/tasks.json"
"zellij/config.kdl" = "/Users/vb/.config/zellij/config.kdl"
"zellij/layouts/default.kdl" = "/Users/vb/.config/zellij/layouts/default.kdl"
"zellij/layouts/dev.kdl" = "/Users/vb/.config/zellij/layouts/dev.kdl"
zshrc = "/Users/vb/.zshrc"

[templates]
