[default.files]
"alacritty" = "~/.config/alacritty"
"aerospace.toml" = "~/.config/aerospace/aerospace.toml"
"helix" = "~/.config/helix"
"nushell" = "~/Library/Application Support/nushell"
"starship.toml" = "~/.config/starship.toml"
"yazi" = "~/.config/yazi"
"zed" = "~/.config/zed"
"zellij" = "~/.config/zellij"
"zshrc" = "~/.zshrc"
